- name: Assert we have needed txt record data
  ansible.builtin.assert:
    quiet: true
    that:
      - cifmw_dnsmasq_txt_record is defined
      - (cifmw_dnsmasq_txt_record | type_debug) == "list"

- name: Assert each txt record element have needed data
  ansible.builtin.assert:
    quiet: true
    that:
      - item.state is defined
      - item.state in ['present', 'absent']
      - item.txt is defined
      - (item.txt | type_debug) == "str"
      - item.name is defined
      - (item.name | type_debug) == "str"
  loop: "{{ cifmw_dnsmasq_txt_record }}"

- name: Add/Remove address
  become: true
  notify: Restart dnsmasq
  ansible.builtin.lineinfile:
    create: true
    path: "{{ cifmw_dnsmasq_basedir }}/txt_records.conf"
    mode: '0644'
    line: >-
      txt-record={{ item.name}},{{item.txt | quote }}
    state: "{{ item.state }}"
    validate: "/usr/sbin/dnsmasq -C %s --test"
  loop: "{{ cifmw_dnsmasq_txt_record }}"
